framework:
    default_locale: pt-br
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - pt-br
            - en
#        providers:
#            crowdin:
#                dsn: '%env(CROWDIN_DSN)%'
#            loco:
#                dsn: '%env(LOCO_DSN)%'
#            lokalise:
#                dsn: '%env(LOKALISE_DSN)%'
