App\Entity\User:
  properties:
    email:
      - NotBlank: ~
  constraints:
    - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
        fields: [email]
        errorPath: email
        message: 'validacao.email.unico'
    - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
        fields: [login]
        errorPath: login
        message: 'validacao.login.unico'

App\Entity\Agenda:
  properties:
    dataInicioAtendimento:
      - NotBlank: ~
    dataFimAtendimento:
      - NotBlank: ~
    horarioInicioAtendimento:
      - NotBlank: ~
    horarioFimAtendimento:
      - NotBlank: ~
    clinica:
      - NotBlank: ~
    medico:
      - NotBlank: ~
  constraints:
    - App\Validator\Constraints\AgendaConstraints: ~

App\Entity\AgendaData:
  properties:
    paciente:
      - NotBlank: {message: 'validacao.notBlank'}
    dataConsulta:
      - NotBlank: {message: 'validacao.notBlank'}
      - DateTime: {message: 'validacao.dateTime'}